services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "55432:5432"  
    environment:
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: vaultpass
      POSTGRES_DB: vaultdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./server
    environment:
      DB_HOST: db
      DB_USER: vault
      DB_PASSWORD: vaultpass
      DB_NAME: vaultdb
      DB_PORT: 5432
      JWT_SECRET: 'vault-super-secret-key-dste-321'
    depends_on:
      - db
    ports:
      - "8787:8787"

volumes:
  pgdata:
