FROM golang:1.25 AS build

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o backend .

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=build /app/backend .
EXPOSE 8787
CMD ["./backend"]